# SPDX-FileCopyrightText: 2026 Jolla Mobile Ltd
#
# SPDX-License-Identifier: BSD-3-Clause

--- # Kaamos Black TOH
override:
  ambience: file:///usr/share/ambience/kaamos-black/kaamos-black.ambience

user-unit:
  description: Set Kaamos Black Ambience
  type: transient-service
  service-type: oneshot
  service-name: set-ambience-to-kaamos-black
  service-exec:
    - "/usr/libexec/jolla-toh-configs/change_ambience.sh"
    - "file:///usr/share/ambience/kaamos-black/kaamos-black.ambience"
  run-on-start: false
